server:
  port: 8080
spring:
  kafka:
    bootstrap:
      servers: ${KAFKA_BOOTSTRAPSERVERS:kafka:29092}
  application:
    name: ms-gestiona-transaction
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/BdPrueba}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres
