server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  kafka:
    bootstrap:
      servers: kafka:29092
  application:
    name: ms-antifraude
  datasource:
    url: jdbc:postgresql://server_postgres:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres

logging:
  level:
    org.hibernate: DEBUG
    org.postgresql: DEBUG
